-- AlterTable
ALTER TABLE "Lead" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "LeadActivity" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
