import type { ThemeConfig } from 'antd'
import {
  BORDERS,
  COLORS,
  SHADOW,
  SPACING,
  FONT,
} from './design-tokens.ts'

export const antdThemeConfig: ThemeConfig = {
  cssVar: {
    key: 'sales-lead-theme',
    prefix: 'sales-lead',
  },
  hashed: false,
  token: {
    colorPrimary: COLORS.black,
    colorInfo: COLORS.info,
    colorSuccess: COLORS.success,
    colorWarning: COLORS.warning,
    colorError: COLORS.error,
    colorText: COLORS.text,
    colorTextSecondary: COLORS.textSecondary,
    colorTextTertiary: COLORS.textTertiary,
    colorTextHeading: COLORS.black,
    colorBgBase: COLORS.surface,
    colorBgContainer: COLORS.surface,
    colorBgLayout: COLORS.pageBg,
    colorFillAlter: COLORS.surfaceMuted,
    colorBorder: COLORS.border,
    colorBorderSecondary: COLORS.borderSecondary,
    colorSplit: COLORS.borderSecondary,
    colorLink: COLORS.black,
    colorLinkHover: COLORS.gray900,
    colorLinkActive: COLORS.black,
    colorIcon: COLORS.gray700,
    colorIconHover: COLORS.black,
    controlOutline: 'rgba(20, 20, 20, 0.08)',
    colorWarningOutline: 'rgba(250, 173, 20, 0.18)',
    colorErrorOutline: 'rgba(255, 77, 79, 0.16)',
    fontFamily: FONT.fontFamily,
    fontSize: FONT.fontSizeMd,
    fontSizeSM: FONT.fontSizeSm,
    fontSizeLG: FONT.fontSizeLg,
    fontSizeHeading1: FONT.fontSizeDisplay,
    fontSizeHeading2: FONT.fontSize2Xl,
    fontSizeHeading3: FONT.fontSizeXl,
    fontWeightStrong: FONT.fontWeightSemibold,
    lineHeight: FONT.lineHeight,
    lineWidth: BORDERS.width,
    lineWidthFocus: 2,
    borderRadius: BORDERS.radiusMd,
    borderRadiusSM: BORDERS.radiusSm,
    borderRadiusLG: BORDERS.radiusLg,
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 46,
    paddingXXS: SPACING.xxs,
    paddingXS: SPACING.xs,
    paddingSM: SPACING.sm,
    padding: SPACING.md,
    paddingMD: SPACING.lg,
    paddingLG: SPACING.xl,
    paddingXL: SPACING.xxl,
    marginXXS: SPACING.xxs,
    marginXS: SPACING.xs,
    marginSM: SPACING.sm,
    margin: SPACING.md,
    marginMD: SPACING.lg,
    marginLG: SPACING.xl,
    marginXL: SPACING.xxl,
    boxShadow: SHADOW.card,
    boxShadowSecondary: SHADOW.dropdown,
  },
  components: {
    Layout: {
      bodyBg: COLORS.pageBg,
      headerBg: COLORS.surface,
      siderBg: COLORS.surface,
      footerBg: COLORS.pageBg,
      triggerBg: COLORS.black,
      triggerColor: COLORS.white,
    },
    Card: {
      bodyPadding: SPACING.cardPadding,
      bodyPaddingSM: SPACING.lg,
      headerHeight: 56,
      headerFontSize: FONT.fontSizeLg,
      headerFontSizeSM: FONT.fontSizeMd,
    },
    Button: {
      fontWeight: FONT.fontWeightSemibold,
      defaultShadow: 'none',
      primaryShadow: 'none',
      dangerShadow: 'none',
      borderColorDisabled: COLORS.border,
      defaultBorderColor: COLORS.border,
      defaultHoverBorderColor: COLORS.black,
      defaultHoverColor: COLORS.black,
      defaultActiveBorderColor: COLORS.black,
      defaultActiveColor: COLORS.black,
    },
    Input: {
      hoverBorderColor: COLORS.black,
      activeBorderColor: COLORS.black,
      activeShadow: '0 0 0 2px rgba(20, 20, 20, 0.06)',
      errorActiveShadow: '0 0 0 2px rgba(255, 77, 79, 0.12)',
      warningActiveShadow: '0 0 0 2px rgba(250, 173, 20, 0.12)',
    },
    Select: {
      activeBorderColor: COLORS.black,
      hoverBorderColor: COLORS.black,
      optionActiveBg: COLORS.gray50,
      optionSelectedBg: COLORS.gray200,
      optionSelectedColor: COLORS.text,
      selectorBg: COLORS.surface,
    },
    Table: {
      headerBg: COLORS.surfaceMuted,
      headerColor: COLORS.text,
      borderColor: COLORS.borderSecondary,
      rowHoverBg: COLORS.gray50,
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
    },
    Descriptions: {
      labelBg: COLORS.surfaceMuted,
      itemPaddingBottom: SPACING.sm,
    },
    Tag: {
      defaultBg: COLORS.surfaceMuted,
      defaultColor: COLORS.text,
    },
    Timeline: {
      tailColor: COLORS.border,
      itemPaddingBottom: SPACING.lg,
    },
  },
}
