import type { ThemeConfig } from 'antd'
import { designTokens } from './design-tokens.ts'

export const antdThemeConfig: ThemeConfig = {
  cssVar: {
    key: 'sales-lead-theme',
    prefix: 'sales-lead',
  },
  hashed: false,
  token: {
    colorPrimary: designTokens.colors.black,
    colorInfo: designTokens.colors.info,
    colorSuccess: designTokens.colors.success,
    colorWarning: designTokens.colors.warning,
    colorError: designTokens.colors.error,
    colorText: designTokens.colors.text,
    colorTextSecondary: designTokens.colors.textSecondary,
    colorTextTertiary: designTokens.colors.textTertiary,
    colorTextHeading: designTokens.colors.black,
    colorBgBase: designTokens.colors.surface,
    colorBgContainer: designTokens.colors.surface,
    colorBgLayout: designTokens.colors.pageBg,
    colorFillAlter: designTokens.colors.surfaceMuted,
    colorBorder: designTokens.colors.border,
    colorBorderSecondary: designTokens.colors.borderSecondary,
    colorSplit: designTokens.colors.borderSecondary,
    colorLink: designTokens.colors.black,
    colorLinkHover: designTokens.colors.gray900,
    colorLinkActive: designTokens.colors.black,
    colorIcon: designTokens.colors.gray700,
    colorIconHover: designTokens.colors.black,
    controlOutline: 'rgba(20, 20, 20, 0.08)',
    colorWarningOutline: 'rgba(250, 173, 20, 0.18)',
    colorErrorOutline: 'rgba(255, 77, 79, 0.16)',
    fontFamily: designTokens.typography.fontFamily,
    fontSize: designTokens.typography.fontSizeMd,
    fontSizeSM: designTokens.typography.fontSizeSm,
    fontSizeLG: designTokens.typography.fontSizeLg,
    fontSizeHeading1: designTokens.typography.fontSizeDisplay,
    fontSizeHeading2: designTokens.typography.fontSize2Xl,
    fontSizeHeading3: designTokens.typography.fontSizeXl,
    fontWeightStrong: designTokens.typography.fontWeightSemibold,
    lineHeight: designTokens.typography.lineHeight,
    lineWidth: designTokens.border.width,
    lineWidthFocus: 2,
    borderRadius: designTokens.border.radiusMd,
    borderRadiusSM: designTokens.border.radiusSm,
    borderRadiusLG: designTokens.border.radiusLg,
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 46,
    paddingXXS: designTokens.spacing.xxs,
    paddingXS: designTokens.spacing.xs,
    paddingSM: designTokens.spacing.sm,
    padding: designTokens.spacing.md,
    paddingMD: designTokens.spacing.lg,
    paddingLG: designTokens.spacing.xl,
    paddingXL: designTokens.spacing.xxl,
    marginXXS: designTokens.spacing.xxs,
    marginXS: designTokens.spacing.xs,
    marginSM: designTokens.spacing.sm,
    margin: designTokens.spacing.md,
    marginMD: designTokens.spacing.lg,
    marginLG: designTokens.spacing.xl,
    marginXL: designTokens.spacing.xxl,
    boxShadow: designTokens.shadow.card,
    boxShadowSecondary: designTokens.shadow.dropdown,
  },
  components: {
    Layout: {
      bodyBg: designTokens.colors.pageBg,
      headerBg: designTokens.colors.surface,
      siderBg: designTokens.colors.surface,
      footerBg: designTokens.colors.pageBg,
      triggerBg: designTokens.colors.black,
      triggerColor: designTokens.colors.white,
    },
    Card: {
      bodyPadding: designTokens.spacing.cardPadding,
      bodyPaddingSM: designTokens.spacing.lg,
      headerHeight: 56,
      headerFontSize: designTokens.typography.fontSizeLg,
      headerFontSizeSM: designTokens.typography.fontSizeMd,
    },
    Button: {
      fontWeight: designTokens.typography.fontWeightSemibold,
      defaultShadow: 'none',
      primaryShadow: 'none',
      dangerShadow: 'none',
      borderColorDisabled: designTokens.colors.border,
      defaultBorderColor: designTokens.colors.border,
      defaultHoverBorderColor: designTokens.colors.black,
      defaultHoverColor: designTokens.colors.black,
      defaultActiveBorderColor: designTokens.colors.black,
      defaultActiveColor: designTokens.colors.black,
    },
    Input: {
      hoverBorderColor: designTokens.colors.black,
      activeBorderColor: designTokens.colors.black,
      activeShadow: '0 0 0 2px rgba(20, 20, 20, 0.06)',
      errorActiveShadow: '0 0 0 2px rgba(255, 77, 79, 0.12)',
      warningActiveShadow: '0 0 0 2px rgba(250, 173, 20, 0.12)',
    },
    Table: {
      headerBg: designTokens.colors.surfaceMuted,
      headerColor: designTokens.colors.text,
      borderColor: designTokens.colors.borderSecondary,
      rowHoverBg: designTokens.colors.gray50,
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
    },
    Descriptions: {
      labelBg: designTokens.colors.surfaceMuted,
      itemPaddingBottom: designTokens.spacing.sm,
    },
    Tag: {
      defaultBg: designTokens.colors.surfaceMuted,
      defaultColor: designTokens.colors.text,
    },
    Timeline: {
      tailColor: designTokens.colors.border,
      itemPaddingBottom: designTokens.spacing.lg,
    },
  },
}
